### ISSUE TITLE
There is already native snipping tool on Windows 7 ?

### ISSUE THREAD

**Issue by anzz1** [vxiiduu/SnippingToolEx#1]
With WinSxS identifier `amd64_microsoft-windows-snippingtool-app_31bf3856ad364e35_6.1.7600.16385_none_f5b8f3d6a353fa89` on x64 version of Win7. So idk really why this need to be pulled from Win10 ?

See attachment: 
[SnippingTool_6.1.7600.16385_amd64.zip](https://github.com/vxiiduu/SnippingToolEx/files/12867117/SnippingTool_6.1.7600.16385_amd64.zip)

```
  File: SnippingTool.exe
CRC-32: 4b7d92ab
   MD5: 7633f554eeafde7f144b41c2fcaf5f63
 SHA-1: 44497c3d6fada0066598a6170b90c53e28ddf96c

  File: SnippingTool.exe.mui
CRC-32: c7d84ada
   MD5: d06d718ada3e72ba84c2a1542f5cc9b6
 SHA-1: 22fbd9576721bbe9c5203f843aa0e82d71ad7f42
```

Actually I prefer the Windows 7 one more since it launch directly to snap creation without clicking New.
And you can create the hotkey (WIN+SHIFT+S or CTRL+PRTSCR) by compiling something like this:

```c
// sniphotkey.c
//

#include <windows.h>

void launch() {
  STARTUPINFO si;
  PROCESS_INFORMATION pi;

  memset(&si, 0, sizeof(STARTUPINFO));
  memset(&pi, 0, sizeof(PROCESS_INFORMATION));

  if(CreateProcessA(NULL, "SnippingTool.exe", NULL, NULL, FALSE, 0, NULL, NULL, &si, &pi)) {
    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);
  }
}

int APIENTRY WinMain(HINSTANCE hInst, HINSTANCE hPrev, LPSTR lpCmdLine, int nCmdShow)
{
  MSG msg;
  BOOL ret;
 
  RegisterHotKey(NULL, 0, MOD_SHIFT | MOD_WIN, 0x53); // WIN+SHIFT+S
  RegisterHotKey(NULL, 1, MOD_CONTROL, VK_SNAPSHOT); // CTRL+PRTSCR

  while((ret = GetMessage(&msg, 0, 0, 0)) != 0) {
    if(ret == -1)
      break;

    if (msg.message == WM_HOTKEY) {
      launch();
    } else {
      TranslateMessage(&msg);
      DispatchMessage(&msg);
    }
  }

  UnregisterHotKey(NULL, 0);
  UnregisterHotKey(NULL, 1);

  return 0;
}
```

**Comment by vxiiduu** [comment]
The one and only purpose of SnippingToolEx is to get the "delay" function, as demonstrated in the screenshots in this repository. I personally do not use it, and I prefer the Win7 snipping tool as well - however, I made this for fun and also because someone on a forum somewhere requested it.

**Comment by anzz1** [comment]
Alrighty, that makes sense. :)
